### PR TITLE
US Infection Level Dialog fix due to API change

### PR DESCRIPTION
**Pull request by mullerj**
The COVID-19 API now includes country code (CountryCode) in addition to country (Country). This change breaks the chatbot tutorial as it is currently implemented: https://developer.ibm.com/tutorials/crisis-communication-chatbot-watson-assistant-webhook-integration-discovery-covid-data/.
The US Infection Level dialog passes "US" which is now the country code. Modified the webhook to use CountryCode instead of Country.
This could also be fixed by changing the dialog to pass "United States of America" which would not require a change to the webhook.

### CODE REVIEW

**Comment by johnwalicki** [comment]
Thanks @mullerj for the investigation and patch!   We will accept it.  I'd like @moficodes to do a quick review.

**Comment by moficodes** [comment]
@mullerj thanks for catching that.
I think we should update the dialog instead of the web-hook. since most other countries will be the country name. 

https://github.com/Call-for-Code/Solution-Starter-Kit-Communication-2020/blob/master/starter-kit/assistant/skill-CDC-COVID-FAQ.json#L2014

This is the line where the country name "US" is passed. Let's change that instead of the web-hook function.

**Comment by mullerj** [comment]
@moficodes No problem, makes sense to update the dialog instead.

**Comment by mullerj** [comment]
@moficodes Updated pull request based on your suggestion to change the dialog instead of the webhook. 
I saw another pull request with the same fix so I closed my pull request without merge to cancel it. Reopened my pull request after I noticed that the other pull request was also closed without merge.

**Pull request merged**
